/* Insertar datos en la colección VACUNA creados por el propio alumno */


db.vacuna.insertMany([

    {
      "nombre": "Ivette",
      "apellido": "Bolton",
      "sexo": "F",
      "fecha_nacimiento": "1946-02-18",
      "localidad": "Serbia",
      "raza": "RZ04",
      "enfermedades_previas": "Hipocondriaco",
      "tratamiento_preexistente": "Xylishield",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Ly",
      "apellido": "Schuelcke",
      "sexo": "M",
      "fecha_nacimiento": "1948-09-01",
      "localidad": "Laos",
      "raza": "RZ05",
      "enfermedades_previas": "hipocondriaco",
      "tratamiento_preexistente": "NITROGEN",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Othelia",
      "apellido": "Hance",
      "sexo": "F",
      "fecha_nacimiento": "1982-04-16",
      "localidad": "Gambia",
      "raza": "RZ05",
      "enfermedades_previas": "Hipocondriaco y afectado por productos alergénicos",
      "tratamiento_preexistente": "Super Restorative Tinted SPF 20 Tint 1",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Artus",
      "apellido": "Fones",
      "sexo": "M",
      "fecha_nacimiento": "1930-04-10",
      "localidad": "Mozambique",
      "raza": "RZ07",
      "enfermedades_previas": "Hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "DIABETIC FOOT DEFENSE",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Laural",
      "apellido": "Coulson",
      "sexo": "F",
      "fecha_nacimiento": "1984-03-03",
      "localidad": "Brasil",
      "raza": "RZ07",
      "enfermedades_previas": "Persona celiaca y alergiada",
      "tratamiento_preexistente": "Orchard Grass, Standardized",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Myrtice",
      "apellido": "Sauvage",
      "sexo": "F",
      "fecha_nacimiento": "1978-06-21",
      "localidad": "Indonesia",
      "raza": "RZ07",
      "enfermedades_previas": "Nunca ha estado enferma",
      "tratamiento_preexistente": "Impact Fix Essence Make Up Base",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Atlanta",
      "apellido": "Hull",
      "sexo": "F",
      "fecha_nacimiento": "2010-04-01",
      "localidad": "Nepal",
      "raza": "RZ03",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Tegretol",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Glyn",
      "apellido": "Elph",
      "sexo": "M",
      "fecha_nacimiento": "1997-12-23",
      "localidad": "Uganda",
      "raza": "RZ02",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de Hipotensión",
      "tratamiento_preexistente": "Excedrin",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Dugald",
      "apellido": "Cameron",
      "sexo": "M",
      "fecha_nacimiento": "1988-07-18",
      "localidad": "Suiza",
      "raza": "RZ05",
      "enfermedades_previas": "Cuadro de hipertensión aguda y alergias múltiples\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Nicardipine Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Sissie",
      "apellido": "Boagey",
      "sexo": "F",
      "fecha_nacimiento": "1964-09-15",
      "localidad": "Israel",
      "raza": "RZ01",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "Midazolam Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Vernen",
      "apellido": "Chatelet",
      "sexo": "M",
      "fecha_nacimiento": "2016-01-08",
      "localidad": "Nepal",
      "raza": "RZ07",
      "enfermedades_previas": "Hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "Phoma",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Ivan",
      "apellido": "Suarez",
      "sexo": "M",
      "fecha_nacimiento": "1957-01-31",
      "localidad": "Ruanda",
      "raza": "RZ07",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "Hand Sanitizer",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Glen",
      "apellido": "Mathieson",
      "sexo": "M",
      "fecha_nacimiento": "1951-05-04",
      "localidad": "Islandia",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Simvastatin",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Evyn",
      "apellido": "Erwin",
      "sexo": "M",
      "fecha_nacimiento": "1940-05-01",
      "localidad": "Dinamarca",
      "raza": "RZ04",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nHipotensión grave",
      "tratamiento_preexistente": "Paroxetine",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Tallie",
      "apellido": "Neame",
      "sexo": "M",
      "fecha_nacimiento": "2000-07-19",
      "localidad": "Tailandia",
      "raza": "RZ03",
      "enfermedades_previas": "Alergggggia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Benadryl",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Gradeigh",
      "apellido": "Geerdts",
      "sexo": "M",
      "fecha_nacimiento": "1944-03-29",
      "localidad": "Vaticano",
      "raza": "RZ04",
      "enfermedades_previas": "Caso leve de hipotensión\nNo tiene alergias",
      "tratamiento_preexistente": "CIPROFLOXACIN",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Jolynn",
      "apellido": "Filipychev",
      "sexo": "F",
      "fecha_nacimiento": "2016-07-18",
      "localidad": "Alemania",
      "raza": "RZ03",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergia a la penicilina",
      "tratamiento_preexistente": "Lyrica",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Alia",
      "apellido": "Leverson",
      "sexo": "F",
      "fecha_nacimiento": "1965-05-02",
      "localidad": "Vietnam",
      "raza": "RZ05",
      "enfermedades_previas": "Alerg#ia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Isopropyl Alcohol",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "James",
      "apellido": "Scoates",
      "sexo": "M",
      "fecha_nacimiento": "2003-12-12",
      "localidad": "Polonia",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Azithromycin",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Ava",
      "apellido": "Rist",
      "sexo": "F",
      "fecha_nacimiento": "1954-11-10",
      "localidad": "Luxemburgo",
      "raza": "RZ02",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "Anastrozole",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Eadie",
      "apellido": "Aronovich",
      "sexo": "F",
      "fecha_nacimiento": "1987-07-05",
      "localidad": "Madagascar",
      "raza": "RZ07",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Metaxalone",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Edward",
      "apellido": "Horsell",
      "sexo": "M",
      "fecha_nacimiento": "1929-03-06",
      "localidad": "Burundi",
      "raza": "RZ01",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Metoclopramide",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Kaye",
      "apellido": "Dutnall",
      "sexo": "F",
      "fecha_nacimiento": "1925-12-09",
      "localidad": "Uganda",
      "raza": "RZ07",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Methylphenidate Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Raphaela",
      "apellido": "Nicklinson",
      "sexo": "F",
      "fecha_nacimiento": "2009-11-22",
      "localidad": "Suiza",
      "raza": "RZ06",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Leader tussin dm max",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Merna",
      "apellido": "Shufflebotham",
      "sexo": "F",
      "fecha_nacimiento": "1968-04-28",
      "localidad": "Serbia",
      "raza": "RZ04",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "benzoyl peroxide",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Elianore",
      "apellido": "Mordin",
      "sexo": "F",
      "fecha_nacimiento": "2008-05-09",
      "localidad": "Suecia",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Clorazepate Dipotassium",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Edithe",
      "apellido": "Death",
      "sexo": "F",
      "fecha_nacimiento": "1989-05-23",
      "localidad": "Serbia",
      "raza": "RZ02",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "MELALEUCA QUINQUENERVIA POLLEN",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Olimpia",
      "apellido": "Sloam",
      "sexo": "F",
      "fecha_nacimiento": "1937-10-16",
      "localidad": "Botsuana",
      "raza": "RZ02",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Azathioprine",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Emanuel",
      "apellido": "Danilchenko",
      "sexo": "M",
      "fecha_nacimiento": "1987-06-16",
      "localidad": "Vietnam",
      "raza": "RZ06",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Flurbiprofen",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Freeland",
      "apellido": "Mouser",
      "sexo": "M",
      "fecha_nacimiento": "1975-09-24",
      "localidad": "Rusia",
      "raza": "RZ07",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "Ludens Original Menthol Throat Drops",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Elaina",
      "apellido": "Troth",
      "sexo": "F",
      "fecha_nacimiento": "1979-11-11",
      "localidad": "Ucrania",
      "raza": "RZ07",
      "enfermedades_previas": "Hipocondriaco",
      "tratamiento_preexistente": "Acetaminophen",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Maegan",
      "apellido": "Barker",
      "sexo": "F",
      "fecha_nacimiento": "1921-06-30",
      "localidad": "Indonesia",
      "raza": "RZ05",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "REVIA",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Wayne",
      "apellido": "Styant",
      "sexo": "M",
      "fecha_nacimiento": "1964-07-02",
      "localidad": "Gambia",
      "raza": "RZ05",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Doxycycline Hyclate",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Cesar",
      "apellido": "Gregson",
      "sexo": "M",
      "fecha_nacimiento": "1988-03-05",
      "localidad": "Mozambique",
      "raza": "RZ02",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Treatment Set TS336851",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Henrieta",
      "apellido": "Soames",
      "sexo": "F",
      "fecha_nacimiento": "1977-04-30",
      "localidad": "España",
      "raza": "RZ06",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Dovonex",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Aubert",
      "apellido": "Leathard",
      "sexo": "M",
      "fecha_nacimiento": "1954-12-24",
      "localidad": "Israel",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Nighttime Sleep Aid",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Sayre",
      "apellido": "Wingrove",
      "sexo": "F",
      "fecha_nacimiento": "1970-01-02",
      "localidad": "Nepal",
      "raza": "RZ05",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "Famotidine",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Andy",
      "apellido": "Bycraft",
      "sexo": "M",
      "fecha_nacimiento": "1940-03-16",
      "localidad": "Congo",
      "raza": "RZ01",
      "enfermedades_previas": "Nunca se sintió enfermo",
      "tratamiento_preexistente": "Budesonide",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Stan",
      "apellido": "Heggison",
      "sexo": "M",
      "fecha_nacimiento": "2010-04-07",
      "localidad": "Senegal",
      "raza": "RZ07",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "Propoxyphene and Acetaminophen",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Joshia",
      "apellido": "Quilty",
      "sexo": "M",
      "fecha_nacimiento": "1951-04-29",
      "localidad": "Croacia",
      "raza": "RZ02",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "Isosorbide Dinitrate",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Bernette",
      "apellido": "Kynston",
      "sexo": "F",
      "fecha_nacimiento": "1953-08-05",
      "localidad": "Mozambique",
      "raza": "RZ04",
      "enfermedades_previas": "Excelente salud\nNunca ha estado enfermo",
      "tratamiento_preexistente": "Cramps Spasms",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Brucie",
      "apellido": "Tropman",
      "sexo": "M",
      "fecha_nacimiento": "2012-04-18",
      "localidad": "Jordania",
      "raza": "RZ01",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergias múltiples a la penicilina y aspirina",
      "tratamiento_preexistente": "Viramune",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Cullie",
      "apellido": "Ogglebie",
      "sexo": "M",
      "fecha_nacimiento": "2010-12-07",
      "localidad": "Albania",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "Dexamethasone",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Harv",
      "apellido": "Shallow",
      "sexo": "M",
      "fecha_nacimiento": "2013-04-13",
      "localidad": "Alemania",
      "raza": "RZ07",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "albuterol sulfate",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Sherilyn",
      "apellido": "Pinson",
      "sexo": "F",
      "fecha_nacimiento": "1970-07-25",
      "localidad": "Botsuana",
      "raza": "RZ03",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "CARMEX original lip balm EXTERNAL ANALGESIC",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Rosco",
      "apellido": "Storr",
      "sexo": "M",
      "fecha_nacimiento": "1965-05-29",
      "localidad": "Gambia",
      "raza": "RZ03",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergias múltiples a la penicilina y paracetamol",
      "tratamiento_preexistente": "Pollens - Weeds and Garden Plants, Ragweed. Western Ambrosia psilostachya",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Martha",
      "apellido": "Bigham",
      "sexo": "F",
      "fecha_nacimiento": "1971-06-07",
      "localidad": "Birmania",
      "raza": "RZ04",
      "enfermedades_previas": "Nunca ha experimentado la sensación de enfermo",
      "tratamiento_preexistente": "leader pain reliever",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Vale",
      "apellido": "Oswal",
      "sexo": "M",
      "fecha_nacimiento": "1951-05-22",
      "localidad": "Nepal",
      "raza": "RZ02",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Allergy",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Dorie",
      "apellido": "Simenon",
      "sexo": "F",
      "fecha_nacimiento": "1929-01-12",
      "localidad": "Bahamas",
      "raza": "RZ05",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "Flawless Finish Dual Perfection Makeup SPF 8 Ivory",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Maureene",
      "apellido": "Verey",
      "sexo": "F",
      "fecha_nacimiento": "1994-02-10",
      "localidad": "Senegal",
      "raza": "RZ02",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Robitussin Peak Cold Sugar-Free Cough Plus Chest Congestion DM",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Borden",
      "apellido": "Disley",
      "sexo": "M",
      "fecha_nacimiento": "2006-06-23",
      "localidad": "Chipre",
      "raza": "RZ06",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "Aspergillus niger",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Pavlov",
      "apellido": "Whelpton",
      "sexo": "M",
      "fecha_nacimiento": "1975-12-16",
      "localidad": "Angola",
      "raza": "RZ04",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Glyburide",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Coop",
      "apellido": "Fullbrook",
      "sexo": "M",
      "fecha_nacimiento": "1920-04-23",
      "localidad": "India",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Witch Hazel",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Wyn",
      "apellido": "Sanja",
      "sexo": "M",
      "fecha_nacimiento": "1967-12-31",
      "localidad": "Ruanda",
      "raza": "RZ03",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "EROS BODYGLIDE",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Teodor",
      "apellido": "Hanselman",
      "sexo": "M",
      "fecha_nacimiento": "2010-11-23",
      "localidad": "Tailandia",
      "raza": "RZ05",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Good Sense Nicotine",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Rodolfo",
      "apellido": "Egleton",
      "sexo": "M",
      "fecha_nacimiento": "1979-06-15",
      "localidad": "Bahamas",
      "raza": "RZ01",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "Methoxsalen",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Vale",
      "apellido": "De Mitri",
      "sexo": "M",
      "fecha_nacimiento": "1947-12-09",
      "localidad": "Mongolia",
      "raza": "RZ03",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Isopropyl Alcohol",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Peggy",
      "apellido": "Pittendreigh",
      "sexo": "F",
      "fecha_nacimiento": "1988-02-16",
      "localidad": "Argentina",
      "raza": "RZ02",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Povidone Iodine",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Jocelyn",
      "apellido": "Nosworthy",
      "sexo": "F",
      "fecha_nacimiento": "1959-10-03",
      "localidad": "Israel",
      "raza": "RZ02",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Instant Hand Sanitizer",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Link",
      "apellido": "Clemendet",
      "sexo": "M",
      "fecha_nacimiento": "2020-01-10",
      "localidad": "Libia",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "ESIKA HD COLOR HIGH DEFINITION COLOR SPF 20",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Avram",
      "apellido": "Gossan",
      "sexo": "M",
      "fecha_nacimiento": "1921-01-29",
      "localidad": "Albania",
      "raza": "RZ04",
      "enfermedades_previas": "Hipocondriaco",
      "tratamiento_preexistente": "Listerine Antiseptic",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Amii",
      "apellido": "Struijs",
      "sexo": "F",
      "fecha_nacimiento": "1993-09-02",
      "localidad": "Jordania",
      "raza": "RZ04",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "age renewal firming and hydrating moisturizer",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Gerhard",
      "apellido": "Schirach",
      "sexo": "M",
      "fecha_nacimiento": "2019-09-21",
      "localidad": "Comoras",
      "raza": "RZ05",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergia a la penicilina",
      "tratamiento_preexistente": "Aspirin",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Bette",
      "apellido": "Packman",
      "sexo": "F",
      "fecha_nacimiento": "2008-08-25",
      "localidad": "Serbia",
      "raza": "RZ01",
      "enfermedades_previas": "Nunca experimentó la sensación de enferma",
      "tratamiento_preexistente": "Vasotec",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Shela",
      "apellido": "Dunmore",
      "sexo": "F",
      "fecha_nacimiento": "2019-03-08",
      "localidad": "Irak",
      "raza": "RZ03",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "ALTERNARIA TENUIS",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Westley",
      "apellido": "Jollie",
      "sexo": "M",
      "fecha_nacimiento": "2011-06-13",
      "localidad": "Polonia",
      "raza": "RZ01",
      "enfermedades_previas": "Hipocondriaco",
      "tratamiento_preexistente": "Flucytosine",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Roslyn",
      "apellido": "Daid",
      "sexo": "F",
      "fecha_nacimiento": "1969-07-08",
      "localidad": "Ghana",
      "raza": "RZ04",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "Meteoric Iron Prunus Immune Support",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Gino",
      "apellido": "Pouck",
      "sexo": "M",
      "fecha_nacimiento": "1922-05-23",
      "localidad": "Luxemburgo",
      "raza": "RZ01",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Malt",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Otho",
      "apellido": "Toward",
      "sexo": "M",
      "fecha_nacimiento": "1951-12-01",
      "localidad": "Filipinas",
      "raza": "RZ04",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Carbidopa and Levodopa",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Nert",
      "apellido": "Blowes",
      "sexo": "F",
      "fecha_nacimiento": "1981-02-06",
      "localidad": "Madagascar",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Arnica e pl. tota 20",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "See",
      "apellido": "Sapsford",
      "sexo": "M",
      "fecha_nacimiento": "1969-06-27",
      "localidad": "Congo",
      "raza": "RZ05",
      "enfermedades_previas": "Nunca ha estado enferme",
      "tratamiento_preexistente": "Pier 1 Imports Sweet Orange Anti-bacterial Hand Wash",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Nevile",
      "apellido": "Nolli",
      "sexo": "M",
      "fecha_nacimiento": "1951-08-12",
      "localidad": "Finlandia",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "L-Methylfolate Calcium",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Romeo",
      "apellido": "Boissier",
      "sexo": "M",
      "fecha_nacimiento": "1930-07-26",
      "localidad": "Rusia",
      "raza": "RZ05",
      "enfermedades_previas": "Nunca ha estado enfermo",
      "tratamiento_preexistente": "White Hickory",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Wolfie",
      "apellido": "Hasley",
      "sexo": "M",
      "fecha_nacimiento": "1923-11-05",
      "localidad": "Burundi",
      "raza": "RZ03",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Jun Wai Lung Medicine",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Mick",
      "apellido": "Olivey",
      "sexo": "M",
      "fecha_nacimiento": "1940-10-17",
      "localidad": "Singapur",
      "raza": "RZ04",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergia a la penicilina",
      "tratamiento_preexistente": "infants pain and fever",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Dyann",
      "apellido": "Terrans",
      "sexo": "F",
      "fecha_nacimiento": "1937-07-06",
      "localidad": "Egipto",
      "raza": "RZ07",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "Differin",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Mohandas",
      "apellido": "Iddenden",
      "sexo": "M",
      "fecha_nacimiento": "1929-04-25",
      "localidad": "Rusia",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "FLEBEAUTE COLLAGENIC SKIN COVER",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Sonny",
      "apellido": "Kiely",
      "sexo": "M",
      "fecha_nacimiento": "1944-12-11",
      "localidad": "Vietnam",
      "raza": "RZ03",
      "enfermedades_previas": "Excelente sistema inmunitario\nHa superado una infección por el virus Ébola",
      "tratamiento_preexistente": "THE BAMBOO OF DAMYANG MOISTURE ESSENCE",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Fidelia",
      "apellido": "Armatys",
      "sexo": "F",
      "fecha_nacimiento": "1927-11-06",
      "localidad": "Bahamas",
      "raza": "RZ02",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "Extra Strength Headache Relief",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Terrance",
      "apellido": "Chasen",
      "sexo": "M",
      "fecha_nacimiento": "1961-02-07",
      "localidad": "Israel",
      "raza": "RZ02",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Servo Stat-Foam",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Ad",
      "apellido": "Montford",
      "sexo": "M",
      "fecha_nacimiento": "1921-06-02",
      "localidad": "Suiza",
      "raza": "RZ07",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "regular strength",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Graham",
      "apellido": "Olner",
      "sexo": "M",
      "fecha_nacimiento": "1940-01-17",
      "localidad": "Senegal",
      "raza": "RZ07",
      "enfermedades_previas": "Cuadro de hipertensión moderada\nSigue tratamientos para otras enfermedades regularmente (ver apartado de tratamiento preexistente para saber la medicación)",
      "tratamiento_preexistente": "CIPRO",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Giusto",
      "apellido": "Janaway",
      "sexo": "M",
      "fecha_nacimiento": "1992-07-20",
      "localidad": "Islandia",
      "raza": "RZ04",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "ANTIBACTERIAL",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Myca",
      "apellido": "Lowne",
      "sexo": "M",
      "fecha_nacimiento": "1954-09-27",
      "localidad": "Mauritania",
      "raza": "RZ01",
      "enfermedades_previas": "Cuadro de hipertensión leve\nSigue tratamientos para otras enfermedades regularmente\nNo tiene problemas cardiacos",
      "tratamiento_preexistente": "Zolpidem Tartrate",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Alicea",
      "apellido": "Gentzsch",
      "sexo": "F",
      "fecha_nacimiento": "1927-04-24",
      "localidad": "Angola",
      "raza": "RZ02",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Diarrhea Relief",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Celesta",
      "apellido": "O'Shevlan",
      "sexo": "F",
      "fecha_nacimiento": "1971-07-31",
      "localidad": "Chile",
      "raza": "RZ06",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "SYAGRUS ROMANZOFFIANA POLLEN",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Vivien",
      "apellido": "Kliesl",
      "sexo": "F",
      "fecha_nacimiento": "1967-02-14",
      "localidad": "Jordania",
      "raza": "RZ04",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "dg health sore throat",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Rod",
      "apellido": "Tombling",
      "sexo": "M",
      "fecha_nacimiento": "1940-09-11",
      "localidad": "Islandia",
      "raza": "RZ02",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "LISINOPRIL",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Kaja",
      "apellido": "Dossit",
      "sexo": "F",
      "fecha_nacimiento": "2016-06-14",
      "localidad": "EEUU",
      "raza": "RZ07",
      "enfermedades_previas": "Alergia a la penicilina\nResponde bien a medicación alternativa",
      "tratamiento_preexistente": "Animal Allergens, Feather Mix",
      "tratamiento_preexistente_dosis_mg": 100,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Wolfy",
      "apellido": "Fallowfield",
      "sexo": "M",
      "fecha_nacimiento": "1935-12-23",
      "localidad": "Luxemburgo",
      "raza": "RZ07",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Ondansetron Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Morlee",
      "apellido": "Raspison",
      "sexo": "M",
      "fecha_nacimiento": "2005-12-06",
      "localidad": "Ucrania",
      "raza": "RZ01",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Phenazopyridine Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Anselm",
      "apellido": "McPhate",
      "sexo": "M",
      "fecha_nacimiento": "1974-07-05",
      "localidad": "Tanzania",
      "raza": "RZ02",
      "enfermedades_previas": "Sistema inmunitario frágil\nPersona celiaca\nAlergia a la penicilina",
      "tratamiento_preexistente": "MLK Kit F2",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Fay",
      "apellido": "Mole",
      "sexo": "F",
      "fecha_nacimiento": "1971-12-25",
      "localidad": "Vietnam",
      "raza": "RZ05",
      "enfermedades_previas": "Cuadro de hipertensión aguda\nNo sigue tratamientos para otras enfermedades regularmente (ver apartado de tratamientos preexistentes para saber la medicación)\nProblemas cardiacos graves\nYa ha sufrido 2 infartos",
      "tratamiento_preexistente": "English Walnut",
      "tratamiento_preexistente_dosis_mg": 3.75,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Maddie",
      "apellido": "Nibley",
      "sexo": "M",
      "fecha_nacimiento": "1966-02-16",
      "localidad": "Mozambique",
      "raza": "RZ04",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Pleo Zinc",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }, {
      "nombre": "Alexander",
      "apellido": "Lyall",
      "sexo": "M",
      "fecha_nacimiento": "1924-11-20",
      "localidad": "Vaticano",
      "raza": "RZ03",
      "enfermedades_previas": "Ha superado una infección por el virus Ébola\nExcelente sistema inmunitario",
      "tratamiento_preexistente": "Cipro",
      "tratamiento_preexistente_dosis_mg": 2.5,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Damaris",
      "apellido": "Quene",
      "sexo": "F",
      "fecha_nacimiento": "1951-12-29",
      "localidad": "Ucrania",
      "raza": "RZ04",
      "enfermedades_previas": "Nunca ha estado enfermo",
      "tratamiento_preexistente": "Antifungal",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Rosella",
      "apellido": "Rubenchik",
      "sexo": "F",
      "fecha_nacimiento": "1942-01-21",
      "localidad": "Comoras",
      "raza": "RZ03",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Sertraline Hydrochloride",
      "tratamiento_preexistente_dosis_mg": 1.25,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Alasteir",
      "apellido": "Banyard",
      "sexo": "M",
      "fecha_nacimiento": "2010-01-06",
      "localidad": "Angola",
      "raza": "RZ07",
      "enfermedades_previas": "Dificultades para mantener circulación sanguinea en niveles adecuados\nCaso grave de hipotensión",
      "tratamiento_preexistente": "Ramipril",
      "tratamiento_preexistente_dosis_mg": 50,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Levy",
      "apellido": "McLugaish",
      "sexo": "M",
      "fecha_nacimiento": "1965-07-04",
      "localidad": "Nepal",
      "raza": "RZ05",
      "enfermedades_previas": "Persona celiaca",
      "tratamiento_preexistente": "BENZTROPINE MESYLATE",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "simple_ciego",
      "placebo": "S",
      "miembro_ensayos_anteriores": "N"
    }, {
      "nombre": "Nils",
      "apellido": "Rundall",
      "sexo": "M",
      "fecha_nacimiento": "1969-11-21",
      "localidad": "Mauritania",
      "raza": "RZ05",
      "enfermedades_previas": "Caso leve de hipotensión",
      "tratamiento_preexistente": "Neomycin and Polymyxin B Sulfates and Bacitracin Zinc",
      "tratamiento_preexistente_dosis_mg": 200,
      "tipo_de_ensayo": "doble_ciego",
      "placebo": "N",
      "miembro_ensayos_anteriores": "S"
    }
    ])